### ISSUE TITLE
wrong "lang" attribute

### ISSUE THREAD

**Issue by sobolevn** [nielsenramon/stacss#4]
When accessing `stacss`'s website, it detects that a language is `Latin`.

Which, I guess, happens because of the content. 
Since the `lang` attribute is not set: https://github.com/nielsenramon/stacss/blob/website/_layouts/default.html#L2

Here's the screenshot. It's in russian, but you got the point.
<img width="1280" alt="2017-04-09 12 18 54" src="https://cloud.githubusercontent.com/assets/4660275/24836228/0466cfd2-1d1f-11e7-9e6a-9601e109e47d.png">

**Comment by nielsenramon** [comment]
@sobolevn Fixed! :-)
