### ISSUE TITLE
[Suggestion] Moving to Stylelint

### ISSUE THREAD

**Issue by FalkoJoseph** [nielsenramon/stacss#5]
As [scss-lint is being deprecated](https://github.com/brigade/scss-lint/blob/master/README.md#notice-consider-other-tools-before-adopting-scss-lint), how about moving to [Stylelint](https://stylelint.io/) or even [sass-lint](https://github.com/sasstools/sass-lint) which seems to be quite close to scss-lint?

Some advantages of Stylelint are

- Ties in closely with build tools like Gulp/Webpack as it's Javascript based.
- Powered by postCSS, so supports any CSS syntax including SCSS and cssnext.
- Fully customisable.
- Used by companies like Facebook.
- Easy to integrate with Travis/Circle etc.

Just an idea, I'm curious about hearing your opinion on this :)

**Comment by nielsenramon** [comment]
Hey @FalkoJoseph I was thinking about just using https://github.com/prettier/prettier to be honest. It's slowly becoming the industry standard. WDYT?

**Comment by nielsenramon** [comment]
Done a while ago!

**Comment by FalkoJoseph** [comment]
Haha, was just looking to clone stacss for a new project.
Glad to see it's integrated! @nielsenramon 👍
